### ISSUE TITLE
No volumes: section. docker-compose: no declaration was found in the volumes section

### ISSUE THREAD

**Issue by vigeland** [Red5d/docker-autocompose#17]
I had test it for example with portainer.
because there is no volumes section, docker-compose raise an error.
docker-compose: no declaration was found in the volumes section

Output:
version: "3"
services:
  portainer:
    container_name: portainer
    entrypoint:
      - /portainer
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    hostname: 744e2324ef35
    image: portainer/portainer-ce
    ipc: private
    logging:
      driver: json-file
      options: {}
    networks:
      - bridge
    ports:
      - 8000:8000/tcp
      - 9000:9000/tcp
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    working_dir: /
networks:
  bridge:

Missing in iml file something like this.
volumes:
  portainer_data:
    external: true

**Comment by Red5d** [comment]
If you run "docker inspect portainer", what does the volume/bind-mount section look like for that container?

**Comment by vigeland** [comment]
for clarification. Output: mean output from the script autocompose and the missing part is need to reimport with  docker-compose up -d. Without the three lines I got the Error.

portainer_data is a volume.
docker volume ls
DRIVER    VOLUME NAME
local     portainer_data

Do you mean this parts ?
  "HostConfig": {
            "Binds": [
                "portainer_data:/data:rw",
                "/var/run/docker.sock:/var/run/docker.sock:rw"
            ],
            "ContainerIDFile": "",
...
 "Mounts": [
            {
                "Type": "volume",
                "Name": "portainer_data",
                "Source": "/var/lib/docker/volumes/portainer_data/_data",
                "Destination": "/data",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
...
      "Image": "portainer/portainer-ce",
            "Volumes": {
                "/data": {},
                "/var/run/docker.sock": {}
            },

**Comment by Red5d** [comment]
I think this has been fixed in some recent updates. Try using the latest image below and see if that fixes the issue.

`docker pull ghcr.io/red5d/docker-autocompose:latest`

**Comment by nikolas-digitalBabylon** [comment]
> I think this has been fixed in some recent updates. Try using the latest image below and see if that fixes the issue.
> 
> `docker pull ghcr.io/red5d/docker-autocompose:latest`

Hi, actually just checked and I see the same issue. Volumes section is missing.

**Comment by damntourists** [comment]
I'm having the same issue.

**Comment by Red5d** [comment]
@damntourists thanks, I've got a really busy weekend, but I'll check on this after. If you've verified that it works, feel free to submit a pull request to change that item and I'll review/merge it.

**Comment by acdoussan** [comment]
running into this same problem, is there an open pr for this?

**Comment by d-EScape** [comment]
I have made a PR of the code above and including some other modifications/fixes.

**Comment by Red5d** [comment]
@d-EScape , thanks! The PR wasn't actually submitted to the repo, but I created one and merged it. I also made an additional commit just now to increase the compose file version number to 3.6 which is necessary for the output compose file to pass validation using "docker-compose config" with the current network/volume config capabilities that have been included in the script recently.

**Comment by Anaerin** [comment]
This appears to still be happening with named volumes. For instance:
```
version: "3"
services:
  grafana:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - AUDIT_CONTROL
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - NET_ADMIN
      - NET_BROADCAST
      - SYSLOG
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - WAKE_ALARM
    container_name: grafana
    entrypoint:
      - /run.sh
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - PATH=/usr/share/grafana/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    hostname: 44f1f25d3954
    image: grafana/grafana:latest
    ipc: shareable
    mac_address: 02:42:ac:11:00:02
    networks:
      - inter-conteiner network
    ports:
      - 3010:3000/tcp
    restart: unless-stopped
    user: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    working_dir: /usr/share/grafana
networks:
  'inter-conteiner network':
    external: true

```
Note lack of volumes section despite a named volume (`grafana`) being defined.

**Comment by Red5d** [comment]
@Anaerin , am I looking at the wrong thing? The compose file in your comment has a volumes section with a "grafana-storage" volume 5-6 lines from the bottom.

**Comment by Anaerin** [comment]
Yes, that's for the container. The image should then be defined in a separate "volumes" section, and as this is using a named volume, it should be declared as "external". For example:
```
version: "3"
services:
  grafana:
    container_name: grafana
    entrypoint:
      - /run.sh
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    hostname: 44f1f25d3954
    image: grafana/grafana:latest
    ipc: shareable
    mac_address: 02:42:ac:11:00:02
    networks:
      - inter-conteiner network
    ports:
      - 3010:3000/tcp
    restart: unless-stopped
    user: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    working_dir: /usr/share/grafana
networks:
  'inter-conteiner network':
    external: true
volumes:
  grafana-storage:
    external: true
```
