### ISSUE TITLE
network_mode: "host" is being translated into a container network named host

### ISSUE THREAD

**Issue by cocoonkid** [Red5d/docker-autocompose#39]
should be network_mode: "host" in docker-compose but it gets created like:
```
    networks:
      - host



networks:
  host:
    external: true
    name: host
```
