### ISSUE TITLE
issue with some entry point

### ISSUE THREAD

**Issue by shuther** [Red5d/docker-autocompose#45]
The generated docker-compose.yml file below is not accepted by docker compose
```
version: "3"
services:
  seafile-memcached:
    container_name: seafile-memcached
    entrypoint:
      - memcached
      - -m
      - 256
```

I had to group the entry point as below to avoid the error (everything in one line)

> services.seafile-memcached.entrypoint.2 must be a string

> entrypoint: memcached -m 256

Hope it helps
