### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by kroese** [Red5d/docker-autocompose#59]
It does not export the SHM value:

`shm_size: 512MB`

Nor the stop timeout value:

`stop_grace_period: 2m`

Nor the static IP address:

```
networks:
      example:
        ipv4_address: 172.18.0.2
```

If these three values could be added that would be really nice.

**Comment by strech345** [comment]
also this was all missing
```
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - type: tmpfs
        target: /tmp
```
